---
# handlers file for fail2ban

- name: " Handler | Loading fail2ban service "
  service:
    name: fail2ban
    state: restarted
    enabled: yes
  register: f2banRestarted
  listen: 'restart f2ban'


