---
# handlers file for fail2ban

- name: " Handler | Loading fail2ban service "
  service:
    name: fail2ban
    state: started
    enabled: yes
  register: f2banRestarted
  listen: 'start f2ban'


